name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        env: 
          DEPLOY_DIRECTORY: ${{ vars.DEPLOY_DIRECTORY }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo $DEPLOY_DIRECTORY
            cd $DEPLOY_DIRECTORY
            git pull origin master
