name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # from https://nextjs.org/docs/pages/guides/ci-build-caching#github-actions
      - name: Prepare Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build Next.js app
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            DEPLOY_DIRECTORY="${{ vars.DEPLOY_DIRECTORY }}"
            mkdir -p $DEPLOY_DIRECTORY
            rm -rf $DEPLOY_DIRECTORY/*

          source-directory: .
          target-directory: $DEPLOY_DIRECTORY
          script-stop-on-error: true

      - name: Transfer Built Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "."
          target: ${{ vars.DEPLOY_DIRECTORY }}
